spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/movieConfig
          searchPaths: '{application}/{profile}'
        label: master

server:
  port: 8030

eureka:
  client:
    service-url:
      defaultZone: http://admin:pass@localhost:8760/eureka,http://admin:pass@localhost:8761/eureka
  instance:
    prefer-ip-address: true
